### ISSUE TITLE
Buy cronic ,but has not arrived

### ISSUE THREAD

**Issue by hiyesok** [Toniq-Labs/cronic-dashboard#1]
I spent 17icp to buy a cronic today. The ICP has been deducted from my wallet, but the cronic has not arrived. What's the matter? Transaction hash value: bc6812e1b88a348a97c641158424c205082292d6faa53ec1045677bfb7c5fe99   
My ICP address: 1adf7a1212af5651404764b2bc05b8f6bdba1819c94de1af2e574d71a929407e

Timestamp | 2021年10月20日 UTC 10:49:46 (今天)

Block | 989221

**Comment by stephenandrews** [comment]
Looks like we found the transaction and it should be in your wallet: https://e3izy-jiaaa-aaaah-qacbq-cai.raw.ic0.app/?tokenid=yqqhr-dqkor-uwiaa-aaaaa-b4aaq-maqca-aadke-a

Can you try adding the tokenid manually?

**Comment by hiyesok** [comment]
Got  it ,thanks   ~

**Comment by stephenandrews** [comment]
No worries thanks!
